config:
  network: ethereum
  chainID: 1
  blockPerDay: 7200
  confirmedBlocks: 2
  nativeToken: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
  wrapToken: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  multicall: "0xcA11bde05977b3631167028862bE2a173976CA11"
  jobs:
    - synchronier
    - selector
    - batchbuilder
  rpcs:
    - https://arbitrum-goerli.blockpi.network/v1/rpc/public 
  zkpayment: "0xbA1D39C6621770fE3738A6E6D1024F58B6e2F810"
  startblock: 31958849             
    # - https://eth-sepolia.public.blastapi.io
    
